### ISSUE TITLE
the plot_tree is null

### ISSUE THREAD

**Issue by liu-felix123** [lmterryn/ITSMe#2]
Hi Louise,
im try to output plot_tree,but its not show.the screenshot as below:
![H1L 2Y@%HMZ}3T5SS2(M%XX](https://user-images.githubusercontent.com/100141618/206074760-c512eb0f-97a7-495c-aef4-44660220dab9.png)

and i following the tutorial to acquired  parameter of basic structural meterics,equally,the summary figure not show.
am i need output the each parameter plot by manully?
![)W%7(2X3ER3ZF{K6L)_JM1N](https://user-images.githubusercontent.com/100141618/206075797-c62520ac-3a64-4004-aba1-08a268f957d0.png)
cheers
Felix.Liu

**Comment by lmterryn** [comment]
Hi Felix

I see that is a small mistake in the tutorial. The element in the output list that holds the plot is not called "plotTree" but "plot". Thanks for pointing this out. So you should H_out$plot to see the plot. I changed the code so that it plots it automatically again when you run the function. 

For the second problem, you have to set the plot parameter TRUE and also include an OUT_path. Then the figure will automatically save in this OUT_path. 

Update the package, and try again :)

**Comment by liu-felix123** [comment]
Thank you.first problem is closed.
the secend problem, should i reference the tutorial as below? it must to setting each parameter and true ,later to acquired plot automatically.
![1`9_ R_L(I 7 S`}B0V{ 7J](https://user-images.githubusercontent.com/100141618/206336534-b934aace-b185-4661-8a19-bf68edd80e48.png)

**Comment by lmterryn** [comment]
With the plot functions you make the calculation and plot for multiple trees that are present in 1 folder. If you fill in a n OUT_path it will save those figures in the output folder. 

I don't understand exactly what your question is.
